name: itch
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.3
  args: ^2.4.2
  crypto: ^3.0.6
  matcher: ^0.12.16+1
  test: ^1.25.8
  xml: ^6.5.0

dev_dependencies:
  lints: ^4.0.0
